apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-catalog
  template:
    metadata:
      labels:
        app: game-catalog
    spec:
      containers:
        - name: game-catalog
          image: game-catalog-service:local
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: game-catalog-service
spec:
  selector:
    app: game-catalog
  ports:
    - port: 80
      targetPort: 3000 # port van npm start 3000 index.js
      nodePort: 30080 # port to use in browser
  type: NodePort
